apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argotest2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: github.com/acutchin-bitpusher/argotest.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: argotest2

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

